# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editprofile.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditProfile(object):
    def setupUi(self, EditProfile):
        EditProfile.setObjectName("EditProfile")
        EditProfile.resize(658, 599)
        EditProfile.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:2px solid rgb(144, 144, 144);")
        self.centralwidget = QtWidgets.QWidget(EditProfile)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 658, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(58, 58, 58);\n"
"border:2px solid rgb(144, 144, 144);\n"
"color:rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(590, 0, 68, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background-color: rgb(58, 58, 58);\n"
"    color: rgb(255, 2, 2);\n"
"    border:2px solid rgb(144, 144, 144);\n"
"    border-left:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 2, 2);\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 70, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(43, 227, 255);\n"
"border:none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 130, 141, 111))
        self.label_2.setStyleSheet("border:1px solid  rgb(193, 193, 193);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Images/defaultperson.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 465, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;\n"
"color: rgb(255, 0, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 420, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 340, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(340, 340, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 500, 491, 0))
        self.frame.setStyleSheet("border:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, -10, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(0, 35, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border:none;\n"
"color: rgb(255, 0, 0);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(130, 520, 381, 41))
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 0, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color:rgb(37, 255, 37);\n"
"    border:1px solid rgb(37, 255, 37);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(37, 255, 37);\n"
"    color:rgb(0, 0, 0);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 0, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color:rgb(37, 255, 37);\n"
"    border:1px solid rgb(37, 255, 37);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(37, 255, 37);\n"
"    color:rgb(0, 0, 0);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(220, 0, 161, 41))
        self.frame_3.setStyleSheet("background-color:rgba(0, 0, 0, 80);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 270, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(450, 430, 121, 31))
        self.frame_5.setStyleSheet("border:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 121, 31))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color:rgb(37, 255, 37);\n"
"    border:1px solid rgb(37, 255, 37);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(37, 255, 37);\n"
"    color:rgb(0, 0, 0);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 0, 31))
        self.frame_6.setStyleSheet("border:none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border:none;\n"
"color: rgb(37, 255, 37);")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:rgb(37, 255, 37);\n"
"    border:1px solid rgb(37, 255, 37);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(37, 255, 37);\n"
"    color:rgb(0, 0, 0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 386, 231, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border:none;\n"
"color: rgb(255, 0, 0);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(340, 386, 231, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border:none;\n"
"color: rgb(255, 0, 0);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        EditProfile.setCentralWidget(self.centralwidget)

        self.retranslateUi(EditProfile)
        QtCore.QMetaObject.connectSlotsByName(EditProfile)

    def retranslateUi(self, EditProfile):
        _translate = QtCore.QCoreApplication.translate
        EditProfile.setWindowTitle(_translate("EditProfile", "MainWindow"))
        self.label_3.setText(_translate("EditProfile", "Artificial Assistant"))
        self.pushButton_5.setText(_translate("EditProfile", "X"))
        self.label.setText(_translate("EditProfile", "Edit Profile"))
        self.lineEdit_4.setPlaceholderText(_translate("EditProfile", "Email"))
        self.lineEdit_2.setPlaceholderText(_translate("EditProfile", "First name"))
        self.lineEdit_3.setPlaceholderText(_translate("EditProfile", "Last name"))
        self.lineEdit_5.setPlaceholderText(_translate("EditProfile", "OTP"))
        self.pushButton_3.setText(_translate("EditProfile", "Back"))
        self.pushButton_4.setText(_translate("EditProfile", "Save Changes"))
        self.lineEdit.setPlaceholderText(_translate("EditProfile", "Username"))
        self.pushButton_2.setText(_translate("EditProfile", "Send OTP"))
        self.label_5.setText(_translate("EditProfile", "Resend 30 sec"))
        self.pushButton.setText(_translate("EditProfile", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditProfile = QtWidgets.QMainWindow()
    ui = Ui_EditProfile()
    ui.setupUi(EditProfile)
    EditProfile.show()
    sys.exit(app.exec_())
