# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forget_username.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_forget_username(object):
    def setupUi(self, forget_username):
        forget_username.setObjectName("forget_username")
        forget_username.resize(681, 461)
        forget_username.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:2px solid rgb(121, 121, 121);")
        self.centralwidget = QtWidgets.QWidget(forget_username)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 681, 41))
        self.label.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"border:2px solid rgb(121, 121, 121);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(615, 0, 69, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 0, 0);\n"
"    background-color:rgba(0,0,0,0);\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,0,0);\n"
"    color:rgb(255,255,255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 100, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(74, 240, 255);\n"
"background-color:rgba(0,0,0,0);\n"
"border:none;")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 210, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px;")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 350, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: rgb(108, 255, 238);\n"
"    border:1px solid rgb(108,255,238);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(108,255,238);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 350, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color: rgb(108, 255, 238);\n"
"    border:1px solid rgb(108,255,238);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(108,255,238);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 260, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);\n"
"border:none;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        forget_username.setCentralWidget(self.centralwidget)

        self.retranslateUi(forget_username)
        QtCore.QMetaObject.connectSlotsByName(forget_username)

    def retranslateUi(self, forget_username):
        _translate = QtCore.QCoreApplication.translate
        forget_username.setWindowTitle(_translate("forget_username", "MainWindow"))
        self.pushButton.setText(_translate("forget_username", "X"))
        self.label_2.setText(_translate("forget_username", "Forget Username"))
        self.lineEdit.setPlaceholderText(_translate("forget_username", "Email address"))
        self.pushButton_2.setText(_translate("forget_username", "Send"))
        self.pushButton_3.setText(_translate("forget_username", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    forget_username = QtWidgets.QMainWindow()
    ui = Ui_forget_username()
    ui.setupUi(forget_username)
    forget_username.show()
    sys.exit(app.exec_())
