# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(1403, 851)
        home.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(home)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 251, 201))
        self.label_12.setStyleSheet("background-color: rgb(41, 113, 121);\n"
"border-right:1px solid rgb(255,255,255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(70, 30, 116, 91))
        self.label_13.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgb(255, 255, 255);")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("images/defaultperson.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(0, 140, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(255,255,255);")
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 300, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 199, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(130, 140, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(255,255,255);")
        self.label_15.setText("")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 240, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 199, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 800, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 199, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(0, 200, 251, 651))
        self.label_18.setStyleSheet("color:rgb(0,0,0);\n"
"border-right:1px solid rgb(255,255,255);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 360, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 199, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_18.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.pushButton_5.raise_()
        self.label_15.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 1401, 40))
        self.label.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/menu.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(1350, 0, 51, 41))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Database/Images/defaultperson.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 401, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../Images/initial.gif"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(170, 90, 1011, 741))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../Images/Aqua.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(-90, 210, 541, 381))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../Images/Iron_Template_1.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(1030, 320, 361, 471))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border:1px solid rgb(43, 153, 255);\n"
"color: rgb(133, 255, 251);")
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setTabChangesFocus(True)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(0, 805, 1401, 51))
        self.label_7.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-top:1px solid rgb(255,255,255)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(540, 90, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(25)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(133, 255, 251);")
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(1010, 20, 411, 271))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Database/Images/wdwdwd.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(1030, 290, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(43, 153, 255);\n"
"color:rgb(255,255,255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(-20, 560, 401, 241))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../Images/Earth.gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(1350, 0, 51, 41))
        self.pushButton.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgb(255, 255, 255)")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.pushButton_2.setStyleSheet("background-color:rgba(0,0,0,0);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 270, 431, 431))
        self.pushButton_3.setStyleSheet("background-color:rgba(0,0,0,0);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(1270, 810, 129, 38))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color:rgb(43, 153, 255);\n"
"    border:1px solid rgb(43, 153, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 153, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(1100, 90, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(133, 255, 251);")
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(1100, 170, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(133, 255, 251);")
        self.label_17.setText("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(4, 810, 129, 38))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    color:rgb(43, 153, 255);\n"
"    border:1px solid rgb(43, 153, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 153, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 40, 0, 811))
        self.frame_3.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setGeometry(QtCore.QRect(0, 0, 1401, 151))
        self.label_19.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(500, 40, 391, 81))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(255,255,255);\n"
"background-color:rgba(0,0,0,0);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(50, 230, 401, 241))
        self.label_21.setStyleSheet("background-color: rgb(33, 33, 33);\n"
"border-radius:30px")
        self.label_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setGeometry(QtCore.QRect(110, 270, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(17)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgba(0,0,0,0);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(80, 330, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color: rgb(255, 255, 255);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 410, 121, 36))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    color: rgb(58, 196, 255);\n"
"    background-color:rgb(0, 0, 0);\n"
"    border:1px solid rgb(58, 196, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(58, 196, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_10.setGeometry(QtCore.QRect(50, 740, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    color: rgb(58, 196, 255);\n"
"    background-color:rgb(0, 0, 0);\n"
"    border:1px solid rgb(58, 196, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(58, 196, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(500, 230, 401, 241))
        self.label_24.setStyleSheet("background-color: rgb(33, 33, 33);\n"
"border-radius:30px")
        self.label_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(610, 270, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(17)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgba(0,0,0,0);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(540, 330, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color: rgb(255, 255, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_11.setGeometry(QtCore.QRect(640, 410, 121, 36))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    color: rgb(58, 196, 255);\n"
"    background-color:rgb(0, 0, 0);\n"
"    border:1px solid rgb(58, 196, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(58, 196, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(950, 230, 401, 241))
        self.label_27.setStyleSheet("background-color: rgb(33, 33, 33);\n"
"border-radius:30px")
        self.label_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(1090, 270, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(17)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgba(0,0,0,0);")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(980, 330, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color: rgb(255, 255, 255);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_12.setGeometry(QtCore.QRect(1090, 410, 121, 36))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    color: rgb(58, 196, 255);\n"
"    background-color:rgb(0, 0, 0);\n"
"    border:1px solid rgb(58, 196, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(58, 196, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_14.setGeometry(QtCore.QRect(1180, 740, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    color: rgb(58, 196, 255);\n"
"    background-color:rgb(0, 0, 0);\n"
"    border:1px solid rgb(58, 196, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(58, 196, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_24.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.pushButton_11.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.pushButton_12.raise_()
        self.pushButton_14.raise_()
        self.label_5.raise_()
        self.label_11.raise_()
        self.label_9.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.textEdit.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.pushButton_13.raise_()
        self.frame_3.raise_()
        self.horizontalLayout.addWidget(self.frame_2)
        home.setCentralWidget(self.centralwidget)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "MainWindow"))
        self.pushButton_5.setText(_translate("home", "Home"))
        self.pushButton_6.setText(_translate("home", "Profile"))
        self.pushButton_7.setText(_translate("home", "Quit"))
        self.pushButton_8.setText(_translate("home", "Features"))
        self.textEdit.setHtml(_translate("home", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_10.setText(_translate("home", "Responses"))
        self.pushButton_4.setText(_translate("home", "Logout"))
        self.pushButton_13.setText(_translate("home", "Features"))
        self.label_20.setText(_translate("home", "Advance Features"))
        self.label_22.setText(_translate("home", "Add application or web"))
        self.label_23.setText(_translate("home", "Use this feature to open the application or websites. This feature is most useful"))
        self.pushButton_9.setText(_translate("home", "Launch"))
        self.pushButton_10.setText(_translate("home", "Back"))
        self.label_25.setText(_translate("home", "Virtual Mouse"))
        self.label_26.setText(_translate("home", "Virtual Mouse is very easy to use click here to launch button. Move the fingers show camera in your laptop or pc"))
        self.pushButton_11.setText(_translate("home", "Launch"))
        self.label_28.setText(_translate("home", "Browser"))
        self.label_29.setText(_translate("home", "Browser is very fastest. This is a internet browser to safe browsing. "))
        self.pushButton_12.setText(_translate("home", "Launch"))
        self.pushButton_14.setText(_translate("home", "Clear all data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home = QtWidgets.QMainWindow()
    ui = Ui_home()
    ui.setupUi(home)
    home.show()
    sys.exit(app.exec_())
