# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_or_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_or_register(object):
    def setupUi(self, login_or_register):
        login_or_register.setObjectName("login_or_register")
        login_or_register.resize(1401, 851)
        login_or_register.setStyleSheet("background-color:rgb(0,0,0);")
        self.centralwidget = QtWidgets.QWidget(login_or_register)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 620, 1401, 181))
        self.label.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 70, 771, 101))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 260, 421, 281))
        self.label_3.setStyleSheet("border-top: 1px solid  rgb(60, 171, 255);\n"
"border-left: 1px solid  rgb(60, 171, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(850, 260, 421, 271))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/assistant.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 660, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(255,255,255);\n"
"background-color:rgb(33,33,33);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(720, 660, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(255,255,255);\n"
"background-color:rgb(33,33,33);")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 710, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:rgb(18, 170, 28);\n"
"    border:1px solid rgb(18, 170, 28);\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(255,255,255);\n"
"    background-color:rgb(18, 170, 28);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 710, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color:rgb(18, 170, 28);\n"
"    border:1px solid rgb(18, 170, 28);\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(255,255,255);\n"
"    background-color:rgb(18, 170, 28);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 800, 1401, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255,255,255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 300, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(60,171,255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(210, 340, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(60,171,255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(210, 370, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(60,171,255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(210, 400, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(60,171,255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(210, 430, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(60,171,255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(210, 460, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(60,171,255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(210, 490, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgb(60,171,255);")
        self.label_14.setObjectName("label_14")
        login_or_register.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_or_register)
        QtCore.QMetaObject.connectSlotsByName(login_or_register)

    def retranslateUi(self, login_or_register):
        _translate = QtCore.QCoreApplication.translate
        login_or_register.setWindowTitle(_translate("login_or_register", "MainWindow"))
        self.label_2.setText(_translate("login_or_register", "Welcome To The Aritificial Assistant"))
        self.label_5.setText(_translate("login_or_register", "New User ?"))
        self.label_6.setText(_translate("login_or_register", "Already Registered ?"))
        self.pushButton.setText(_translate("login_or_register", "Registration"))
        self.pushButton_2.setText(_translate("login_or_register", "Login"))
        self.label_7.setText(_translate("login_or_register", "© 2021 Artificial Assistant Virtual Assistant | Designed by Prashik Likhar"))
        self.label_8.setText(_translate("login_or_register", "I will assisting you a few commands like,"))
        self.label_9.setText(_translate("login_or_register", "-->  Playing music"))
        self.label_10.setText(_translate("login_or_register", "-->  Open browser"))
        self.label_11.setText(_translate("login_or_register", "-->  Google search"))
        self.label_12.setText(_translate("login_or_register", "-->  Wheather in mumbai"))
        self.label_13.setText(_translate("login_or_register", "-->  Send message"))
        self.label_14.setText(_translate("login_or_register", "-->  Play youtube video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_or_register = QtWidgets.QMainWindow()
    ui = Ui_login_or_register()
    ui.setupUi(login_or_register)
    login_or_register.show()
    sys.exit(app.exec_())
