# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mouse(object):
    def setupUi(self, Mouse):
        Mouse.setObjectName("Mouse")
        Mouse.resize(701, 481)
        self.frame = QtWidgets.QFrame(Mouse)
        self.frame.setGeometry(QtCore.QRect(0, 0, 701, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 41))
        self.label.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);\n"
"border:1px solid rgb(143, 143, 143);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 701, 441))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:1px solid rgb(143, 143, 143);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(330, 10, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(630, 0, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 0, 0);\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(255, 0, 0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(60, 80, 581, 361))
        self.label_4.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgb(200, 200, 200);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(290, 230, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Mouse)
        QtCore.QMetaObject.connectSlotsByName(Mouse)

    def retranslateUi(self, Mouse):
        _translate = QtCore.QCoreApplication.translate
        Mouse.setWindowTitle(_translate("Mouse", "Dialog"))
        self.label_3.setText(_translate("Mouse", "Mouse"))
        self.pushButton.setText(_translate("Mouse", "X"))
        self.label_5.setText(_translate("Mouse", "Please wait..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mouse = QtWidgets.QDialog()
    ui = Ui_Mouse()
    ui.setupUi(Mouse)
    Mouse.show()
    sys.exit(app.exec_())
