# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QrCode.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QrCode(object):
    def setupUi(self, QrCode):
        QrCode.setObjectName("QrCode")
        QrCode.resize(621, 651)
        QrCode.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:2px solid rgb(121, 121, 121);")
        self.label = QtWidgets.QLabel(QrCode)
        self.label.setGeometry(QtCore.QRect(0, 0, 621, 41))
        self.label.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"border:2px solid rgb(121, 121, 121);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(QrCode)
        self.label_2.setGeometry(QtCore.QRect(150, 60, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(74, 240, 255);\n"
"background-color:rgba(0,0,0,0);\n"
"border:none;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(QrCode)
        self.label_3.setGeometry(QtCore.QRect(70, 150, 481, 361))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(QrCode)
        self.pushButton.setGeometry(QtCore.QRect(130, 560, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(108, 255, 238);\n"
"    border:1px solid rgb(108,255,238);\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(108,255,238);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(QrCode)
        self.label_4.setGeometry(QtCore.QRect(230, 300, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;\n"
"color:rgb(240, 240, 240);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(QrCode)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 560, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: rgb(108, 255, 238);\n"
"    border:1px solid rgb(108,255,238);\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(108,255,238);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(QrCode)
        QtCore.QMetaObject.connectSlotsByName(QrCode)

    def retranslateUi(self, QrCode):
        _translate = QtCore.QCoreApplication.translate
        QrCode.setWindowTitle(_translate("QrCode", "Dialog"))
        self.label_2.setText(_translate("QrCode", "Scan Qr Code"))
        self.pushButton.setText(_translate("QrCode", "Back"))
        self.label_4.setText(_translate("QrCode", "Please wait..."))
        self.pushButton_2.setText(_translate("QrCode", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QrCode = QtWidgets.QDialog()
    ui = Ui_QrCode()
    ui.setupUi(QrCode)
    QrCode.show()
    sys.exit(app.exec_())
