# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showprofile.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowProfile(object):
    def setupUi(self, ShowProfile):
        ShowProfile.setObjectName("ShowProfile")
        ShowProfile.resize(905, 588)
        ShowProfile.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:2px solid rgb(144, 144, 144);")
        self.label = QtWidgets.QLabel(ShowProfile)
        self.label.setGeometry(QtCore.QRect(90, 80, 201, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Images/defaultperson.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(ShowProfile)
        self.lineEdit.setGeometry(QtCore.QRect(90, 290, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(ShowProfile)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 360, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(ShowProfile)
        self.lineEdit_3.setGeometry(QtCore.QRect(480, 360, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(ShowProfile)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 430, 661, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(ShowProfile)
        self.label_2.setGeometry(QtCore.QRect(760, 450, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(37, 255, 37);\n"
"border:none")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(ShowProfile)
        self.pushButton.setGeometry(QtCore.QRect(310, 510, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(37, 255, 37);\n"
"    color:rgb(37, 255, 37);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(37, 255, 37);\n"
"    color:rgb(0, 0, 0)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(ShowProfile)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 911, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(58, 58, 58);\n"
"border:2px solid rgb(144, 144, 144);\n"
"color:rgb(255, 255, 255)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(ShowProfile)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 0, 65, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(58, 58, 58);\n"
"    color: rgb(255, 2, 2);\n"
"    border:none;\n"
"    border:2px solid rgb(144, 144, 144);\n"
"    border-left:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 2, 2);\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(ShowProfile)
        QtCore.QMetaObject.connectSlotsByName(ShowProfile)

    def retranslateUi(self, ShowProfile):
        _translate = QtCore.QCoreApplication.translate
        ShowProfile.setWindowTitle(_translate("ShowProfile", "Dialog"))
        self.lineEdit.setPlaceholderText(_translate("ShowProfile", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("ShowProfile", "First Name"))
        self.lineEdit_3.setPlaceholderText(_translate("ShowProfile", "Last Name"))
        self.lineEdit_4.setPlaceholderText(_translate("ShowProfile", "Email"))
        self.label_2.setText(_translate("ShowProfile", "Verified"))
        self.pushButton.setText(_translate("ShowProfile", "Edit"))
        self.label_3.setText(_translate("ShowProfile", "Artificial Assistant"))
        self.pushButton_2.setText(_translate("ShowProfile", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShowProfile = QtWidgets.QDialog()
    ui = Ui_ShowProfile()
    ui.setupUi(ShowProfile)
    ShowProfile.show()
    sys.exit(app.exec_())
